apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: gfdmkewzj-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:7229513a85aaae5c506c565faa72e781e60ae877@sha256:271b2b1c484e7fcebf17da0e13023e9f4d2d74dd4de9ecc84acb70467d22cf5a
          name: container-image
